name: test-github-actions
run-name: ${{ github.actor }} actions test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  hello-world-job:
    runs-on: ubuntu-latest
    name: Hello World Job
    steps:
      - name: Hello World Action step
        id: hello
        uses: wcyn/hello-world-composite-action@main
        with:
          who-to-greet: "Monica_Composite_Test"
      # Use the output from the `hello` step
      - name: Get the random number
        run: echo random-number ${{ steps.hello.outputs.random-number }}
        shell: bash
